name: Github Action Demo on Econtact NodeJS Application
run-name: ${{github.actor}}

on:
    pull_request:
      branches: [ master ]
      paths:
        - econtact_server/**
        - econtact_server/build

jobs:
    nodejs_setup:
        name: NodeJS Development Github Actions test
        runs-on: ubuntu-latest
        defaults:
          run:
           working-directory: ./econtact_server
        # permissions:
        #   contents: write
        #   pull-requests: write
        #   repository-projects: write
        #   issues: write


        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: NodeJS setup
              uses: actions/setup-node@v4

            - name: NPM run build
              if: steps.dep-installation.outcome && steps.eslint.outcome == 'success'
              continue-on-error: true
              id: build
              run: npm run build

            - name: Handle Issue for NPM run build
              uses: iyinka/workshop/.github/actions/issues-handler@dev-issues
              with:
                  outcome: ${{steps.build.outcome}}
                  label: build-failed
                  title: build-failed


